# Generated by Django 5.1.6 on 2025-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_width', models.FloatField(default=0.0)),
                ('_height', models.FloatField(default=0.0)),
                ('_position_x', models.FloatField(default=0.0)),
                ('_position_y', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
